# Prefix
unbind r
bind r source-file ~/.tmux.conf
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Options
set -g mouse on
set -g default-terminal "tmux-256color"

# 3. Load Plugins FIRST (but don't run TPM yet)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux#v2.1.0'

# Catppuccin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_status_background "#242638"
set -g @catppuccin_window_left_separator "  "
set -g @catppuccin_window_text "  #W  "
set -g @catppuccin_window_current_text "  #W  "

# Status bar
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
# set -g status-right "#{E:@catppuccin_status_application}"
# Ensure the zoom module is actually included in the status-right
# Custom Zoom Module
set -g @catppuccin_status_zoom "#{?window_zoomed_flag,#[fg=#{@thm_yellow}]󰁌 Zoomed ,}"
set -g status-right "#{E:@catppuccin_status_session}#{E:@catppuccin_status_application}#{E:@catppuccin_status_zoom}"
# set -g status-right "#{E:@catppuccin_status_session}#{E:@catppuccin_status_application}#{E:@catppuccin_status_zoom}"
set-window-option -g status-position top

run -b "~/.tmux/plugins/tpm/tpm"
